import Ingredient from "./ingredient.js" 


const ingredients = {
    legumes: new Ingredient("Бобові", 45),
    potatoes: new Ingredient("Картопля", 150),
    freshCorn: new Ingredient("Свіжа кукурудза", 150),
    flakes: new Ingredient("Пластівці", 45),
    bulgur: new Ingredient("Булгур", 45),
    buckwheat: new Ingredient("Гречка", 45),
    rice: new Ingredient("Рис (не шліфований)", 45),
    cereals: new Ingredient("Крупи", 45),
    wholeGrainFlour: new Ingredient("Цільнозернове борошно", 45),
    bread: new Ingredient("Хлібці", 65),
    wholeGrainBread: new Ingredient("Цільнозерновий хліб", 70),
    macaroni: new Ingredient("Макарони", 45),
    pita: new Ingredient("Лаваш", 65),
    leanMilk: new Ingredient("Молоко до 2.5%", 200),
    leanKefir: new Ingredient("Кефір до 2.5%", 200),
    leanYoghurt: new Ingredient("Йогурт (не солодкий) до 2.5%", 200),
    oilyMilk: new Ingredient("Молоко від 2.5%", 360),
    oilyKefir: new Ingredient("Кефір від 2.5%", 360),
    oilyYoghurt: new Ingredient("Йогурт (не солодкий) від 2.5%", 370),
    veal: new Ingredient("Телятина", 150),
    liver: new Ingredient("Печінка", 150),
    сhickenFillet: new Ingredient("Куряче філе", 175),
    turkeyFillet: new Ingredient("Індиче філе", 175),
    leanFish: new Ingredient("Риба (до 5% жиру)", 180),
    oilyFish: new Ingredient("Риба (від 5% жиру)", 120),
    eggs: new Ingredient("Яйця", 3), // add counter
    seafood: new Ingredient("Морепродукти", 200),
    vegetables: new Ingredient("Овочі", 300),
    mushrooms: new Ingredient("Гриби", 300),
    oil: new Ingredient("Олія", 10),
    tset: new Ingredient("Майонез", 13),
    avocado: new Ingredient("Авокадо", 55),
    olives: new Ingredient("Оливки", 70),
    mayonnaise: new Ingredient("Гірчиця", 24),
    curd: new Ingredient("Сир зернистий (творог 5% жиру)", 160),
    cheese: new Ingredient("Сир (м'який, твердий, плавлений)", 55),
    sourCream: new Ingredient("Сметана", 110),
    butter: new Ingredient("Масло", 27),
    fat: new Ingredient("Сало", 19),
    fruitsAndBerries: new Ingredient("Фрукти та ягоди", 250),
    bannanas: new Ingredient("Банани", 150),
    grape: new Ingredient("Виноград", 150),
    persimmon: new Ingredient("Хурма", 150),
    mango: new Ingredient("Манго", 150),
    walnut: new Ingredient("Грецький горіх", 20),
    nutsAndSeeds: new Ingredient("Горіхи та насіння", 20),
    sweets: new Ingredient("Солодощі, снеки, ковбаса", 55),
}

export default ingredients;